spring:
#  profiles:
#    active: dev
  application:
    name: CLOUD-API
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
server:
  port: 18052
  tomcat:
    uri-encoding: UTF-8

#eureka:
#  instance:
#    leaseRenewalIntervalInSeconds: 10
#    leaseExpirationDurationInSeconds: 30
#    preferIpAddress: true
#    instanceId: ${spring.cloud.client.ipAddress}:${server.port}
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/